[build]
  command = "npm install --force && vite build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/ssr-home"
  status = 200
